name: Build and Push Nginx Image

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-nginx.yml'
      - 'Dockerfile'
      - 'nginx.conf'
  schedule:
    # Run every day at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/nginx-stream

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.version-check.outputs.should-build }}
      nginx-version: ${{ steps.version-check.outputs.nginx-version }}
    steps:
      - name: Check nginx version
        id: version-check
        run: |
          # Get the actual nginx version that would be installed in Alpine
          echo "Getting nginx version from Alpine..."
          LATEST_VERSION=$(docker run --rm alpine:latest sh -c '
            apk add --no-cache nginx >/dev/null 2>&1
            nginx -v 2>&1 | sed -n "s/.*nginx\/\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p"
          ')
          
          echo "Detected nginx version: $LATEST_VERSION"
          
          # Validate version format
          if ! echo "$LATEST_VERSION" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' >/dev/null; then
            echo "Invalid version format: $LATEST_VERSION"
            exit 1
          fi
          
          # Check if we already have an image with this specific version tag
          echo "Checking if version-specific image already exists..."
          VERSION_EXISTS="false"
          
          if docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$LATEST_VERSION >/dev/null 2>&1; then
            VERSION_EXISTS="true"
            echo "Image with version $LATEST_VERSION already exists"
          else
            echo "No image found for version $LATEST_VERSION"
          fi
          
          # Set output
          echo "nginx-version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          
          # Determine if we should build
          SHOULD_BUILD="false"
          
          # Only build on manual trigger or when version doesn't exist
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SHOULD_BUILD="true"
            echo "Manual trigger - will build"
          elif [ "${{ github.event_name }}" = "push" ]; then
            SHOULD_BUILD="true"
            echo "Configuration files changed - will build"
          elif [ "$VERSION_EXISTS" = "false" ]; then
            SHOULD_BUILD="true"
            echo "Version $LATEST_VERSION not found in registry - will build"
          else
            SHOULD_BUILD="false"
            echo "Version $LATEST_VERSION already exists in registry - skipping build"
          fi
          
          echo "should-build=$SHOULD_BUILD" >> $GITHUB_OUTPUT

  # ... rest of the jobs remain the same

  build-and-push:
    needs: check-version
    if: needs.check-version.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate nginx version
        run: |
          if ! echo "${{ needs.check-version.outputs.nginx-version }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Invalid nginx version: ${{ needs.check-version.outputs.nginx-version }}"
            exit 1
          fi
          echo "Using nginx version: ${{ needs.check-version.outputs.nginx-version }}"

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ needs.check-version.outputs.nginx-version }},enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Nginx with Stream Module
            org.opencontainers.image.description=Alpine-based Nginx with stream module for TCP/UDP load balancing
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            nginx.version=${{ needs.check-version.outputs.nginx-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Create release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nginx-${{ needs.check-version.outputs.nginx-version }}
          name: Nginx ${{ needs.check-version.outputs.nginx-version }}
          body: |
            🚀 **Automated build with nginx version ${{ needs.check-version.outputs.nginx-version }}**
            
            ## Features
            - ✅ Alpine Linux base (minimal size)
            - ✅ Nginx with stream module enabled
            - ✅ Multi-architecture support (amd64, arm64)
            - ✅ Security hardened configuration
            - ✅ Performance optimizations
            - ✅ Health check endpoint at `/health`
            
            ## Usage
            ```bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.check-version.outputs.nginx-version }}
            docker run -p 80:80 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ```
            
            ## Image Details
            - **Registry**: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}`
            - **Tags**: `latest`, `${{ needs.check-version.outputs.nginx-version }}`
            - **Digest**: `${{ steps.build.outputs.digest }}`
          generate_release_notes: true
          make_latest: true

  security-scan:
    needs: [check-version, build-and-push]
    if: needs.check-version.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'